### PR TITLE
Controllable Normal Map  for Water Scripts

### PR DESCRIPTION
**Pull request by valina354**
I noticed that the water normal map seems hard coded, so i decided to add a new param, i tested it and it seems to work fine with no performance drops so i think it should be merged, if anything seems wrong or incorrect edits can be made

### CODE REVIEW

**Comment by valina354** [comment]
example of how param is used in a water script
image

**Comment by valina354** [comment]
btw @TheOverfloater  make sure to check out this pull request

**Comment by TheOverfloater** [comment]
I'll do the merge once I have the time for testing, most likely during the weekend.

**Comment by valina354** [comment]
i dont really use pathos anymore but im guessing both of my pull-requests have been forgotten? its been months already

**Comment by TheOverfloater** [comment]
> i dont really use pathos anymore but im guessing both of my pull-requests have been forgotten? its been months already

I haven't forgotten about your PRs, it's just that the public release of Pathos is not in my top priorities right now. I will eventually merge them when I get around to it.

**Comment by TheOverfloater** [comment]
@valina354 I've merged the changes now.

**Comment by valina354** [comment]
> @valina354 I've merged the changes now.

ok, is it ok if i do make more pull requests with important things i added on my fork that would make this engine better? since even tho i dont really use this engine anymore (due to fact its missing model lightmaps is my main reasoning) i want to ensure this engine is best it can be

**Comment by TheOverfloater** [comment]
> > @valina354 I've merged the changes now.
> 
> ok, is it ok if i do make more pull requests with important things i added on my fork that would make this engine better? since even tho i dont really use this engine anymore (due to fact its missing model lightmaps is my main reasoning) i want to ensure this engine is best it can be

Can you give a brief rundown of what you have changed? I don't promise I can merge everything, or that I'll be able to do it soon. It depends on my workload and available free time when and what I can merge.

**Comment by valina354** [comment]
> > > @valina354 I've merged the changes now.
> > 
> > 
> > ok, is it ok if i do make more pull requests with important things i added on my fork that would make this engine better? since even tho i dont really use this engine anymore (due to fact its missing model lightmaps is my main reasoning) i want to ensure this engine is best it can be
> 
> Can you give a brief rundown of what you have changed? I don't promise I can merge everything, or that I'll be able to do it soon. It depends on my workload and available free time when and what I can merge.

well some things i added on my fork are:
Water Flowmapping
Texture AO Mapping (as in those AO textures you see in PBR)
Math_Counter entity
Vignette, Filmgrain, Chromatic abberation and black and white postprocess entities

**Comment by valina354** [comment]
oh, and theres also model shadows (tho of course makes model black but could be used in combination with model light or what it was), there was also of course Parallax Mapping but it was broken

do they sound important for pathos?

**Comment by valina354** [comment]
oh i also forgot to mention that i made my own sledge fork, and got it fully working with pathos, not sure if that would be usefull, considering fact i see in newer commits reference of modifable lightmap scale and smoothing groups

**Comment by valina354** [comment]
if i do more pull requests, do i do all in 1 or seperate pull requests? @TheOverfloater

**Comment by TheOverfloater** [comment]
Please raise one PR, and I will merge it as time allows.

**Comment by valina354** [comment]
> Please raise one PR, and I will merge it as time allows.

ok, i guess in PR i will just add the stuff that worked on my custom fork? (so no parallax mapping (which worked but didnt with dlights)) and im guessing related to my custom sledge fork wont PR that too

**Comment by TheOverfloater** [comment]
Yeah, only add what is working please. For the Sledge fork, it would be better if you just gave me that via a drive link or something, if its not available elsewhere. If I'll do something with it, that'd be a repo of its own.

**Comment by valina354** [comment]
> Yeah, only add what is working please. For the Sledge fork, it would be better if you just gave me that via a drive link or something, if its not available elsewhere. If I'll do something with it, that'd be a repo of its own.

yup, here is the sledge fork https://github.com/Soft-Sprint-Studios/Matrix_Engine/tree/main/pathos/sources/codesrc/utils/parallaxed its well based on hammertime which is a sledge fork that fixed sledge mostly and my fork made compatibility better with pathos slightly

**Comment by TheOverfloater** [comment]
Alright, thanks! I'll end up modifying Sledge once I motivate myself to start using C# once more.

**Comment by valina354** [comment]
pullrequest done https://github.com/TheOverfloater/pathos-public/pull/49

**Pull request merged**
