### PR TITLE
Some intresting things

### PR DESCRIPTION
**Pull request by valina354**
Added:
Water Flowmapping
Chromatic Abberation,Vignette, black and white effect
texture AO mapping
math_counter

Changed:
Made cubemaps build in cubemaps/ instead of main folder
Made filmgrain work with an entity
Spelling fix in envdlight.cpp

Issues:
this was made before many major updates, it might require heavy reworking and i might have also missed adding some code, if so then its most likely at https://github.com/Soft-Sprint-Studios/Matrix_Engine

math_counter only works with set params rn, due to fact pathos has no IO system

### CODE REVIEW

**Comment by TheOverfloater** [comment]
Thank you. I will slowly merge these as I have time available.

**Comment by valina354** [comment]
> Thank you. I will slowly merge these as I have time available.

yup, hopefully these improvements will help pathos become better, i would have really used pathos since it was best engine i have tried. but fact it doesnt have model lightmapping has stopped me from doing that, which im guessing will probably never be added?

**Comment by TheOverfloater** [comment]
> > Thank you. I will slowly merge these as I have time available.
> 
> yup, hopefully these improvements will help pathos become better, i would have really used pathos since it was best engine i have tried. but fact it doesnt have model lightmapping has stopped me from doing that, which im guessing will probably never be added?

The problem is, quite frankly, that model lightmapping is not only beyond my skills, especially in the math department, but also I have numerous misgivings, even if I could do it:
 - The memory/vram footprint would be huge. You'd need decent resolution model lightmaps to have something usable, which would kick disk space/vram usage sky-high.
 - The models would need to not change at all after levels are compiled.
 - The shader responsible for model rendering is already enormously bloated and I have no idea how to reduce it. Adding this feature would bloat it even further and make shader compile times a nightmare.
 - The problem of dealing with UV coords that overlap in the model.

Also I just feel like it's beyond the scope of Pathos in general, which is really just a slightly Source-ified Half-Life 1 engine mimic. It's just not a modern engine and was never really meant to be like one. If it was, I would've gone with something more like the Doom 3 engine in terms of lighting/level format.

**Comment by valina354** [comment]
> > > Thank you. I will slowly merge these as I have time available.
> > 
> > 
> > yup, hopefully these improvements will help pathos become better, i would have really used pathos since it was best engine i have tried. but fact it doesnt have model lightmapping has stopped me from doing that, which im guessing will probably never be added?
> 
> The problem is, quite frankly, that model lightmapping is not only beyond my skills, especially in the math department, but also I have numerous misgivings, even if I could do it:
> 
> * The memory/vram footprint would be huge. You'd need decent resolution model lightmaps to have something usable, which would kick disk space/vram usage sky-high.
> * The models would need to not change at all after levels are compiled.
> * The shader responsible for model rendering is already enormously bloated and I have no idea how to reduce it. Adding this feature would bloat it even further and make shader compile times a nightmare.
> * The problem of dealing with UV coords that overlap in the model.
> 
> Also I just feel like it's beyond the scope of Pathos in general, which is really just a slightly Source-ified Half-Life 1 engine mimic. It's just not a modern engine and was never really meant to be like one. If it was, I would've gone with something more like the Doom 3 engine in terms of lighting/level format.

i think a way around most of those issues is using vertex bumped lighting instead, it doesnt need vram other then loading the data, shouldnt have issue with UV, hopefully wouldnt bloat shader too much, infact source engine does it and i think math would be more simpler, but im not sure

**Comment by TheOverfloater** [comment]
Well, that does sound more reasonable. Such ideas are always worth an experiment I guess... somewhere down the line. Maybe when I really have time and sanity to spare I would try to implement something akin to his into RAD.

**Comment by valina354** [comment]
> Well, that does sound more reasonable. Such ideas are always worth an experiment I guess... somewhere down the line. Maybe when I really have time and sanity to spare I would try to implement something akin to his into RAD.

ok, also i just realized i forgot to add some things to this pull requests, do i just do a new commit then on my fork that has the pullrequest adding the new stuff i forgot?

i really wonder what this engine will look like in few years or something which is why im taking time of making pullrequests and stuff to help engine become better

**Comment by TheOverfloater** [comment]
I actually wouldn't mind if you waited with another PR until I am done merging all the changes. What are the missing things you want to add?

**Comment by valina354** [comment]
made new PR, should be final things that i will pullrequest, hopefully all these improvements have helped pathos :)

**Pull request merged**
